<?php

namespace Tests\Feature;

use App\Models\CourseRepository;
use Tests\TestCase;

class CourseRepositoryTest extends TestCase
{
    private $repo;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->repo = new CourseRepository();
    }

    /**
     * @return void
     */
    public function testGetAllCoursesMethod()
    {
        $res = $this->repo->getAllCourses();
        $this->assertIsArray($this->repo->getAllCourses());
        $this->assertContainsOnlyInstancesOf(\App\Models\CourseDescription::class, $res);
    }

    public function testCourseMethod()
    {
        $res = $this->repo->getCourse('Blender');
        $this->assertInstanceOf(\App\Models\CourseDescription::class, $res);
    }
}
